Rats = Card:new{
  guid = "f250cb",
  cost = 4,
  debt = 0,
  potion = 0,
  types = { CardTypes.Action },
}

function Rats:setup (obj)
  position = obj.getPosition()
  deck = obj.clone({ position = {x=position.x, y=position.y + 0.1, z=position.z} })
  for i=1,18 do
    clone = obj.clone({ position = {x=position.x, y=position.y + (0.01*i), z=position.z} })
    deck = deck.putObject(clone)
  end
end
