YoungWitch = Card:new{
  guid = "42a0b8",
  cost = 4,
  debt = 0,
  potion = 0,
  types = { CardTypes.Action, CardTypes.Attack },
}

function YoungWitch:banePile (selectionPool)
  baneSelectionPool = arrayFilter(selectionPool, function(card) return card.cost == 2 or card.cost == 3 end)
  card = table.remove(baneSelectionPool, 1)
  obj = getObjectFromGUID(card.guid)
  card:setup(obj, {-10.00, 1.03, 9.00})
end
